name: delivery_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.6 <6.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  go_router: ^9.0.2
  intl: ^0.17.0
  mason_cli: ^0.1.0-dev.51
  flutter_iconly: any
  flutter_datetime_picker: ^1.5.1
  loader_overlay: ^2.3.0
  loading_indicator: ^3.1.1
  pin_code_fields: ^8.0.1
  bottom_navy_bar: ^6.0.0
  flutter_svg: ^2.0.5
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  path_provider: ^2.0.15

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1

  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter_gen:
  output: lib/gen

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/animation/
    - assets/icons/
