name: delivery_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.6 <6.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^9.0.2
  intl: ^0.17.0
  mason_cli: ^0.1.0-dev.51

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1

  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter_gen:
  output: lib/gen

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/image/
      - assets/svg/
      - assets/animation/
